--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlackCatDevel0per/Hologram
branches:
  - main
projects:
  Hologram:
    path: ""
    icon: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: 1.0.0
...
