# Файл конфигурации для голограм
# Внимание! Плагин не работает без FormAPI!

 #  _   _       _   _           _____             
 # | \ | |     | | (_)         |  __ \            
 # |  \| | __ _| |_ ___   _____| |  | | _____   __
 # | . ` |/ _` | __| \ \ / / _ \ |  | |/ _ \ \ / /
 # | |\  | (_| | |_| |\ V /  __/ |__| |  __/\ V / 
 # |_| \_|\__,_|\__|_| \_/ \___|_____/ \___| \_/  
 # Больше плагинов в https://vk.com/native_dev
 # По вопросам native.dev@mail.ru
 # Этот плагин форк(клон) плагина https://github.com/fuyutsuki/Texter

# доступные языки (en_us, ru_ru,)
locale: ru_ru

# Проверка обновлений [ пока не работает :) ]
check.update: false

# Использование всех команд плагина
can.use.commands: true

# Использование команд плагина только оператором
can.use.only.op: false

# Ограничение количества символов, если это не нужно, установите его равным -1
char: 50

# Количество переносов строк, если это не нужно, установите его на -1
feed: 3

# Укажите миры, в которых не работают голограммы;
world:
  # - world
  # - world2
